version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile # Remplacez par le nom réel de votre Dockerfile Nuxt.js
    ports:
      - "3000:3000" # Assurez-vous que le port exposé correspond à celui de votre application Nuxt.js
    volumes:
      - .:/app # Montez le répertoire local dans le répertoire de travail du conteneur
    environment:
      - NODE_ENV=development # Définissez l'environnement Node.js (par exemple, development)
